EMBEDDINGS = "swow_associative_embeddings.csv"
VOCAB = "vocab.csv"
BASE_CFG = "base.cfg"
START_SYMBOL = "S"
N_GENERATED_WORDS = 250
N_GENERATED_SENTENCES = 20 
MIN_SENTENCES = 5
MAX_SENTENCES = 8
MIN_STANZA_LEN = 2
MAX_STANZA_LEN = 5
SENTENCE_SPLIT_SIZE = 3
MIN_SENTENCE_PARTITION = 2
MAX_SENTENCE_PARTITION = 4

